spring:
  config:
    activate:
      on-profile: h2
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS airport
    driverClassName: org.h2.Driver
    username: root
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2